AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution with SSL - Final version'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name

Resources:
  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for NiroSubs Frontend

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: NiroSubs Frontend Distribution
        DefaultRootObject: index.html
        
        # No custom domains for initial deployment
        # Will add after successful creation
        
        # S3 Origin
        Origins:
          - Id: S3Origin
            DomainName: dev-nirosubs-frontend.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        
        PriceClass: PriceClass_100
      
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: NiroSubs

  # Update S3 bucket policy
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: dev-nirosubs-frontend
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: 's3:GetObject'
            Resource: 'arn:aws:s3:::dev-nirosubs-frontend/*'

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: ns-cloudfront-distribution-id
  
  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: ns-cloudfront-domain
  
  CloudFrontURL:
    Description: CloudFront URL
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: ns-cloudfront-url