AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple CloudFront distribution with SSL'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  
  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:816454053517:certificate/f301d219-515c-4e8c-8cf9-f36b42af428a
    Description: ACM Certificate ARN

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

Resources:
  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: OAI for NiroSubs

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'NiroSubs Frontend - ${Environment}'
        DefaultRootObject: index.html
        
        # Custom domain aliases
        Aliases:
          - !If
            - IsProduction
            - visualforge.ai
            - !Sub '${Environment}.visualforge.ai'
        
        # SSL Certificate
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        
        # S3 Origin
        Origins:
          - Id: S3Origin
            DomainName: !Sub 'dev-nirosubs-frontend.s3.${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        
        PriceClass: PriceClass_100
        
        Tags:
          - Key: Environment
            Value: !Ref Environment
          - Key: Project
            Value: NiroSubs

  # Update S3 bucket policy to allow CloudFront access
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: dev-nirosubs-frontend
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOAI}'
            Action: 's3:GetObject'
            Resource: 'arn:aws:s3:::dev-nirosubs-frontend/*'

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: cloudfront-distribution-id
  
  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: cloudfront-domain
  
  CloudFrontURL:
    Description: CloudFront URL with custom domain
    Value: !If
      - IsProduction
      - https://visualforge.ai
      - !Sub 'https://${Environment}.visualforge.ai'
    Export:
      Name: cloudfront-url