AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 DNS configuration for VisualForge environments'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prod]
    Description: Environment name
  
  HostedZoneId:
    Type: String
    Default: Z015790023056BKZ15UTB
    Description: Route53 Hosted Zone ID for visualforge.ai
  
  CloudFrontDistributionId:
    Type: String
    Description: CloudFront Distribution ID
  
  CloudFrontDomainName:
    Type: String
    Description: CloudFront Distribution Domain Name
  
  ApiGatewayDomainName:
    Type: String
    Description: API Gateway Domain Name

Conditions:
  IsProduction: !Equals [!Ref Environment, prod]
  IsNotProduction: !Not [!Equals [!Ref Environment, prod]]

Resources:
  # Main domain (www or environment prefix)
  MainDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If 
        - IsProduction
        - visualforge.ai
        - !Sub '${Environment}.visualforge.ai'
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront Hosted Zone ID
        EvaluateTargetHealth: false

  # WWW subdomain (production only)
  WwwDomainRecord:
    Type: AWS::Route53::RecordSet
    Condition: IsProduction
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: www.visualforge.ai
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  # API subdomain
  ApiDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If
        - IsProduction
        - api.visualforge.ai
        - !Sub 'api-${Environment}.visualforge.ai'
      Type: A
      AliasTarget:
        DNSName: !Ref ApiGatewayDomainName
        HostedZoneId: Z1UJRXOUMOOFQ8  # API Gateway Hosted Zone ID for us-east-1
        EvaluateTargetHealth: false

  # Auth subdomain
  AuthDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If
        - IsProduction
        - auth.visualforge.ai
        - !Sub 'auth-${Environment}.visualforge.ai'
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !Sub '${Environment}-ns-auth.auth.us-east-1.amazoncognito.com'

  # Media services subdomain
  MediaDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !If
        - IsProduction
        - media.visualforge.ai
        - !Sub 'media-${Environment}.visualforge.ai'
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  MainDomain:
    Description: Main application domain
    Value: !If
      - IsProduction
      - https://visualforge.ai
      - !Sub 'https://${Environment}.visualforge.ai'
    Export:
      Name: !Sub '${Environment}-main-domain'
  
  ApiDomain:
    Description: API domain
    Value: !If
      - IsProduction
      - https://api.visualforge.ai
      - !Sub 'https://api-${Environment}.visualforge.ai'
    Export:
      Name: !Sub '${Environment}-api-domain'
  
  AuthDomain:
    Description: Auth domain
    Value: !If
      - IsProduction
      - https://auth.visualforge.ai
      - !Sub 'https://auth-${Environment}.visualforge.ai'
    Export:
      Name: !Sub '${Environment}-auth-domain'
  
  MediaDomain:
    Description: Media services domain
    Value: !If
      - IsProduction
      - https://media.visualforge.ai
      - !Sub 'https://media-${Environment}.visualforge.ai'
    Export:
      Name: !Sub '${Environment}-media-domain'